name: twomble
favicon: null
layout_spectrum: 0.71984
typography_spectrum: 0.5567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#192a3a'
    - '#294f8e'
    - '#fefefe'
    - '#7b8ca6'
    - '#a5b4c7'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
